---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
  - name: instance-rocky
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
